name = "diode_sim"
uuid = "0ea6e308-b47a-4881-9faa-74520296bb91"
version = "0.1.0"
authors = ["rorkela <sarthakmishraindia@gmail.com>"]

[deps]
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
Gtk = "1.3.1"
LinearAlgebra = "1.12.0"
Plots = "1.41.3"
UnicodePlots = "3.8.1"
